# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]
  


env:
  DSS_VERSION: 11.4.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Package plugin before release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -r dss-plugin-trend-visionone-$GITHUB_REF_NAME.zip ./ -x "*/.*" -x ".*"
    
    - name: Create release and publish package
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dss-plugin-trend-visionone-*.zip
